name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main # (ou 'master', conforme seu branch principal)

permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.2"
          channel: 'stable'
          cache: 'true'

      - name: Get dependencies (root)
        run: flutter pub get

      - name: Get dependencies (web)
        run: flutter pub get
        working-directory: web

      - name: Build web
        run: flutter build web --release --base-href /pilulasdoconhecimento/
        working-directory: web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build/web
